apiVersion: apps/v1
kind: Deployment
metadata:
  name: hellogo
  namespace: flux-system
spec:
  replicas: 1
  selector:
    matchLabels:
      app: web
  template:
    metadata:
      labels:
        app: web
    spec:
      containers:
        - name: api
          image: 487086244836.dkr.ecr.us-east-1.amazonaws.com/hellogo:latest
          ports:
            - containerPort: 8080
